### ISSUE TITLE
Mismatch dimension in Dual-Softmax Filtering

### ISSUE THREAD

**Issue by sitongsu** [cvlab-kaist/DirecT2V#3]
C_dual has the same shape with Softmax(QK^T). While Attention is not the same shape with Softmax(QK^T). I was wondering whether there is something wrong with (1-M) * Attention(Q,K,V)

**Comment by SusungHong** [comment]
'C_dual' is actually averaged across the last dimension and then broadcasted when thresholded to a quantile. Sorry for the confusion.
